[Wednesday.first_nech]
time = "11:30–13:00"
auditorium = "Ауд. Актовый зал (1216/0 (усл))"
address = "ул.Ломоносова, д.9, лит. М"
subject = "ИНФОРМАТИКА (ЛЕК)"
week = "нечетная"
teacher = "Балакшин Павел Валерьевич"

[Wednesday.first_chet]
time = "13:30-15:00"
auditorium = "Ауд. Актовый зал (1216/0 (усл))"
address = "ул.Ломоносова, д.9, лит. М"
subject = "ИНФОРМАТИКА (ЛЕК)"
week = "четная"
teacher = "Гаврилов Антон Валерьевич"

[Wednesday.second_nech]
time = "13:30-15:00"
auditorium = "Ауд. Актовый зал (1216/0 (усл))"
address = "ул.Ломоносова, д.9, лит. М"
subject = "Основы профессиональной деятельности (ЛЕК)"
week = "нечетная"
teacher = "Клименков Сергей Викторович"

[Saturday.first_nech]
time = "09:50-11:20"
auditorium = "Ауд. 2435/3"
address = "Кронверкский пр., д.49, лит.А"
subject = "Программирование (ЛАБ)"
week = "нечетная"
teacher = "Кобелев Роман Павлович"

[Saturday.first_chet]
time = "13:30-15:00"
auditorium = "Ауд. 1404"
address = "Кронверкский пр., д.49, лит.А"
subject = "История России и мира в ХХ веке (ЛЕК)"
week = "четная"
teacher = "Пригодич Никита Дмитриевич"

[Saturday.second_nech]
time = "11:30–13:00"
auditorium = "Ауд. 2435/3"
address = "Кронверкский пр., д.49, лит.А"
subject = "Программирование (ЛАБ)"
week = "нечетная"
teacher = "Кобелев Роман Павлович"

[Saturday.second_chet]
time = "20:30-22:00"
auditorium = "Ауд. 1404"
address = "Кронверкский пр., д.49, лит.А"
subject = "История России и мира в ХХ веке (ЛЕК)"
week = "четная"
teacher = "Павловская Анастасия Юрьевна"
